version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    volumes:
      - backend-data:/backend-app
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    volumes:
      - frontend-data:/frontend-app
    depends_on:
      - backend
volumes:
  backend-data:
  frontend-data:
